steps:
  - id: 'create-env'
    name: 'gcr.io/$PROJECT_ID/python-cloudbuild' # Cloud Build automatically substitutes $PROJECT_ID for your Project ID.
    entrypoint: '/bin/bash'
    args: ['-c','virtualenv /workspace/venv' ]
  - id: 'install-project'
    name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
    entrypoint: 'venv/bin/pip'
    args: ['install', '-V', '-e', '.[dev]']
    waitFor: ['create-env']
  - id: 'type-test'
    name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
    entrypoint: 'venv/bin/python'
    args: ['-m', 'pytype', 'ecmwf_pipeline/', '-v', '2']
    waitFor: ['install-project']
  - id: 'unit-test'
    name: 'gcr.io/$PROJECT_ID/python-cloudbuild'
    entrypoint: 'venv/bin/python'
    args: ['setup.py', 'test']
    waitFor: ['install-project']

timeout: 3600s # 1 hour, just in case.
